[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "HR2B3kYmiNpm4tjHpW58NNrwea2Hdkcc3BSwSrnRzzVe"
week_1_challenge = "39GWCSZQBSPk6gouzFfpwMhkzAJ9Umr1Hvo3fRiDkua7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
